# Generated by Django 4.2.10 on 2026-06-07 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='零件名称')),
                ('model_number', models.CharField(max_length=200, verbose_name='型号规格')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('compatible_models', models.TextField(blank=True, verbose_name='适配说明')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('min_stock', models.IntegerField(default=5, verbose_name='最低库存预警')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '零件',
                'verbose_name_plural': '零件',
                'db_table': 'tf_part',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('battery', '电池'), ('crown', '表冠'), ('crystal', '表镜'), ('movement', '机芯配件'), ('strap', '表带'), ('other', '其他')], max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '零件分类',
                'verbose_name_plural': '零件分类',
                'db_table': 'tf_part_category',
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '库存调整')], max_length=10, verbose_name='类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='关联单号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.part', verbose_name='零件')),
            ],
            options={
                'verbose_name': '库存记录',
                'verbose_name_plural': '库存记录',
                'db_table': 'tf_stock_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.partcategory', verbose_name='分类'),
        ),
    ]
